const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;},text=(node,value)=>{const v=String(value??'');if(node.textContent!==v)node.textContent=v;};
let data={inputs:[],outputs:[]},connected=false,online=false,visible=true,busy=false,tab='inputs',base='',epoch=0,mojo=null,mojoInputs=[],discovering=false,polling=false,deviceSignature='',cameraView='',speed='fine';
const terminalRecordingStates=new Map();
const cards=new Map(),controls=new Map(),locks=new Set(),pending=new Map(),versions=new Map(),sentAt=new Map(),acknowledged=new Map();const mojoStates=new Map();let commandTimer=null,cameraSending=false,pendingTarget=null;
const call=async m=>{if(!pollingAllowed()&&!['state','forget'].includes(m.type))throw Error('Panel is hidden; request paused.');const r=await chrome.runtime.sendMessage(m);if(!r?.ok)throw Error(r?.error||'Extension unavailable. Reload this page.');return r.data;};const note=t=>text($('#status'),t);let writes=Promise.resolve();const write=m=>{const job=writes.catch(()=>{}).then(()=>call(m));writes=job.catch(()=>{});return job;};
const shapes={headset:'<path d="M4 13v-2a8 8 0 0 1 16 0v2M5 12H3v7h4v-7zM19 12h2v7h-4v-7zM19 19v2h-6"/>',return:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4m2-8-4-3 4-3M10 10h7"/>',camera:'<rect x="3" y="6" width="13" height="12" rx="2"/><path d="m16 10 5-3v10l-5-3"/>',eject:'<path d="m4 14 8-10 8 10zM4 19h16"/>',power:'<path d="M12 3v9M6.3 5.7a8 8 0 1 0 11.4 0"/>',link:'<path d="m10 14 4-4M8 16l-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0M16 8l2-2a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/>',record:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/>'};
function icon(type,label){const b=el('button',undefined,'icon-button');b.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true">${shapes[type]}</svg>`;b.append(el('span',label));return b;}
function button(label,fn,cls=''){const b=el('button',label,cls);b.onclick=fn;return b;}
function anyHeld(){return [...controls.values()].some(c=>c.rocker.active);}
function update(d){for(const i of d.inputs){const state=terminalRecordingStates.get(base+':'+i.id);if(state&&state.uid===i.uid&&i.connected)i.deviceRecording=state.recording;else if(state)terminalRecordingStates.delete(base+':'+i.id);}data=d;if(source)source=d.inputs.find(i=>i.id===source.id)||null;for(const k of selected)if(!d.outputs.some(o=>o.key===k&&!o.locked))selected.delete(k);mojoInputs=mojoInputs.map(i=>d.inputs.find(x=>x.id===i.id&&x.uid===i.uid)).filter(i=>i?.connected);for(const i of d.inputs)if(i.isMojo&&i.connected&&!mojoInputs.some(x=>x.id===i.id))mojoInputs.push(i);if(mojo&&(!d.inputs.find(i=>i.id===mojo.input)?.connected||d.inputs.find(i=>i.id===mojo.input)?.uid!==mojo.deviceUID)){stopRockers();mojo=null;note('MoJo device disconnected.');}}
function stopRockers(){for(const c of controls.values())c.rocker.stop();}
const selected=new Set();let source=null,gridView='';
function switchTab(t){stopRockers();tab=t;mojo=null;selected.clear();if(t!=='outputs')source=null;render();requestPreviewNow();}
function createCard(key,isInput=true){const card=el('article',undefined,'tile'),main=el('button',undefined,'tile-main'),tagline=el('div',undefined,'tagline'),tag=el('span'),state=el('span',undefined,'state'),name=el('h3',undefined,'name'),sub=el('p',undefined,'subline'),bar=el('div',undefined,'tile-controls'),power=icon('power','ON'),rec=icon('record','REC HUB'),deviceRec=icon('record','REC TX'),camera=icon('camera','CAM'),eject=icon('eject','EJECT');tagline.append(tag,state);main.append(tagline,name,sub);card.append(main,bar);bar.append(power);if(isInput)bar.append(rec,deviceRec,camera);bar.append(eject);const copy=icon('link','LINK');copy.title='Copy stream link';bar.append(copy);const entry={key,isInput,card,main,tag,state,name,sub,power,rec,deviceRec,camera,eject,copy,item:null};
 copy.onclick=()=>openStreamLinks(entry.item);
 main.onclick=()=>{const i=entry.item;if(tab==='mojo'){openMojo(i);return;}if(isInput){source=i;tab='outputs';selected.clear();}else selected.has(i.key)?selected.delete(i.key):selected.add(i.key);render();requestPreviewNow();};
 power.onclick=()=>isInput?inputAction(entry.item,'inputPower',entry.item.enabled?'disable':'enable'):outputAction('outputControl',entry.item.enabled?'disable':'enable',[key]);rec.onclick=()=>inputAction(entry.item,'inputControl',[2,4].includes(entry.item.recorderStatus)?'stop':'start','streamhubRecord');deviceRec.onclick=()=>terminalRecord(entry.item);camera.onclick=()=>openMojo(entry.item);eject.onclick=()=>isInput?inputAction(entry.item,'inputEject'):outputAction('outputControl','clear',[key]);
 entry.assign=button('Select source',()=>isInput?openInputSources(entry.item):openOutputSources(entry.item),'source-select');const sourceRow=el('div',undefined,'source-row');sourceRow.append(entry.assign);if(isInput){entry.unitControls=el('div',undefined,'unit-controls');entry.intercom=icon('headset','INTERCOM');entry.videoReturn=icon('return','RETURN');entry.intercom.onclick=()=>toggleIntercom(entry.item);entry.videoReturn.onclick=()=>openReturnPicker(entry.item);entry.unitControls.append(entry.intercom,entry.videoReturn);sourceRow.append(entry.unitControls);}card.insertBefore(sourceRow,bar);return entry;
}
function syncCard(c,i){c.item=i;c.copy.hidden=c.isInput?!i.canCopyLink:i.type!=='IP'||!i.canCopyLink;c.copy.disabled=!online;c.copy.title='Copy stream link';const unavailable=busy||!online||locks.has(c.key)||(!c.isInput&&i.locked);c.card.classList.toggle('selected',!c.isInput&&selected.has(i.key));c.main.disabled=unavailable;text(c.tag,c.isInput?`StreamHub Input ${i.id}`:`${i.type}${i.type==='IP'?' · '+i.mode:' '+i.id}`);text(c.state,c.isInput?(i.status===2?'LIVE':i.status===3?'ERROR':i.connected?'CONNECTED':i.protocolId>=0?'ASSIGNED':'AVAILABLE'):i.locked?'LOCKED':i.enabled?'ON':'OFF');c.state.classList.toggle('live',c.isInput?i.status===2:i.enabled);text(c.name,i.name);c.sub.hidden=true;text(c.sub,i.source?`Input ${i.source} · ${data.inputs.find(x=>x.id===i.source)?.name||i.sourceName||''}`:'Unassigned');
 c.power.disabled=unavailable||(c.isInput?!i.canPower:!i.powerAvailable);c.power.title=c.isInput&&!i.canPower?'Select an input profile before starting the stream':'Start or stop stream';c.power.classList.toggle('on',!!i.enabled);text(c.power.querySelector('span'),i.enabled?'ON':'OFF');c.rec.hidden=!c.isInput;c.rec.disabled=unavailable||i.recorderStatus===0||(!i.connected&&i.protocolId<0);c.rec.classList.toggle('recording',[2,4].includes(i.recorderStatus));c.deviceRec.hidden=!c.isInput||!i.canLive;c.deviceRec.disabled=unavailable;c.deviceRec.classList.toggle('recording',i.deviceRecording===true);c.deviceRec.title=i.deviceRecording===true?'Terminal recording ON — stop recording':i.deviceRecording===false?'Terminal recording OFF — start recording':'Terminal recording state unavailable';c.camera.hidden=!c.isInput||!i.isMojo;c.camera.disabled=unavailable;c.eject.disabled=unavailable||(c.isInput?!i.canEject:!i.powerAvailable||i.ejectAvailable===false);c.eject.title=c.isInput?'Detach source from this input':i.ejectHint||'Remove output from dashboard; retain its saved profile';if(c.isInput&&typeof syncNativeButtons==='function')syncNativeButtons(c,i,unavailable); if(c.assign){c.assign.hidden=c.isInput&&(tab==='mojo'||i.canLive&&i.connected);c.assign.disabled=unavailable||(c.isInput?i.canLive&&i.connected:!i.powerAvailable);text(c.assign,c.isInput?(i.protocolId>=0?'Change source':'Select source'):(i.source?`Input ${i.source} · ${data.inputs.find(x=>x.id===i.source)?.name||i.sourceName||''}`:i.encoder?`Encoder ${i.encoder}`:'Available ▾'));}if(c.isInput)syncPreviewCard(c,i);else syncOutputPreview(c,i);
}
function render(){parent.postMessage({type:'sh-preview-session',base:connected?base:'',serverIdentity:data.serverIdentity||null,visible:visible&&pollingAllowed()},'*');$('#login').hidden=connected;$('#workspace').hidden=!connected;$('#connect').disabled=busy;$('#forget').disabled=busy;text($('#endpoint'),base);for(const b of document.querySelectorAll('[data-tab]')){b.classList.toggle('active',b.dataset.tab===tab);b.disabled=busy||navigating;}
 const cameraOpen=tab==='mojo'&&!!mojo;$('#workspace').classList.toggle('rcp-open',cameraOpen);$('#grid').hidden=cameraOpen;$('#camera').hidden=!cameraOpen;
 const grid=$('#grid');if(tab==='encoders'){renderEncoderGrid(grid);}else if(!cameraOpen){const list=tab==='inputs'?data.inputs:tab==='outputs'?data.outputs:mojoInputs,isInput=tab!=='outputs',view=isInput?'inputs':'outputs';if(gridView!==view){cards.clear();grid.replaceChildren();gridView=view;}const keys=new Set(list.map(i=>isInput?'IN:'+i.id:i.key));for(const [key,c]of cards)if(!keys.has(key)){c.card.remove();cards.delete(key);}grid.querySelector('.empty')?.remove();list.forEach((i,n)=>{const key=isInput?'IN:'+i.id:i.key;let c=cards.get(key);if(!c){c=createCard(key,isInput);cards.set(key,c);}syncCard(c,i);c.card.dataset.outputGroup=isInput?'':i.type;if(grid.children[n]!==c.card)grid.insertBefore(c.card,grid.children[n]||null);});if(!isInput)renderOutputAdds(grid);if(!list.length&&isInput)grid.append(el('div',tab==='mojo'?(discovering?'Checking connected devices…':'No connected MoJo Pro devices.'):'No outputs reported by StreamHub.','empty'));}
 renderActions(cameraOpen);for(const k of controls.keys())syncControl(k);document.querySelectorAll('#camera .camera-choice button').forEach(b=>b.disabled=!online||busy);
}
let actionsKey='';function renderActions(cameraOpen){const a=$('#actions');a.replaceChildren();if(cameraOpen){const list=[...mojoInputs].sort((a,b)=>a.id-b.id),index=list.findIndex(i=>i.id===mojo.input);const previous=button('←',()=>navigateMojo(-1)),next=button('→',()=>navigateMojo(1));previous.setAttribute('aria-label','Previous MoJo');next.setAttribute('aria-label','Next MoJo');previous.disabled=next.disabled=busy||!online||navigating||list.length<2;a.append(previous,el('span',`StreamHub Input ${mojo.input} · ${index+1}/${list.length}`,'device-position'),next,button('Devices',()=>{stopRockers();mojo=null;render();}));const i=data.inputs.find(i=>i.id===mojo.input);if(i){const bar=el('div',undefined,'rcp-transport'),c=createCard('IN:'+i.id);syncCard(c,i);bar.append(c.power,c.rec,c.deviceRec,c.intercom,c.videoReturn);a.append(bar);}}
 else if(tab==='outputs'){if(source){const take=button('ASSIGN',()=>outputAction('route',undefined,[...selected]),'primary');take.disabled=busy||!online||!selected.size;a.append(take,button('Cancel',()=>switchTab('inputs')));}else{for(const [label,action]of [['ON','enable'],['OFF','disable'],['EJECT','clear']]){const b=button(label,()=>outputAction('outputControl',action,[...selected]));b.disabled=busy||!online||!selected.size;a.append(b);}}}text($('#selection'),tab==='outputs'?`${selected.size} selected`:'');}
async function outputAction(type,action,keys){if(!keys.length)return;const input=source?.id;await runAction(async()=>{for(const k of keys)locks.add(k);render();let d;try{d=await write({type,action,input,keys});}finally{for(const k of keys)locks.delete(k);}if(d.snapshot)update(d.snapshot);note(d.results.map(r=>`${r.ok?'✓':'!'} ${r.message}`).join(' · '));if(d.results.length&&d.results.every(r=>r.ok)){selected.clear();if(type==='route')switchTab('inputs');}},'outputs');}
function picker(title){const d=el('dialog');d.append(el('h2',title));const list=el('div',undefined,'output-picker');d.append(list,button('Close',()=>{d.close();d.remove();}));document.body.append(d);d.showModal();return {d,list};}
async function copyStreamLink(url){
 // Run synchronous copying during the click, within the active modal dialog.
 url.focus();url.select();url.setSelectionRange(0,url.value.length);
 try{if(document.execCommand('copy'))return;}catch{}
 if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(url.value);return;}
 throw Error('Clipboard unavailable.');
}
function openStreamLinks(item){
 const {list}=picker(`${item.name} · Stream links`);
 const links=item.links||[];
 for(const link of links){const label=el('label',link.label),row=el('div',undefined,'stream-link-row'),url=el('input');url.value=link.url;url.readOnly=true;url.setAttribute('aria-label',link.label);url.onclick=()=>url.select();const copy=button('⧉ Copy',async()=>{try{await copyStreamLink(url);copy.textContent='✓ Copied';note('Stream link copied.');setTimeout(()=>{copy.textContent='⧉ Copy';},1500);}catch{url.focus();url.select();note('Clipboard access denied. The URL is selected for manual copying.');}});copy.title='Copy '+link.label;copy.setAttribute('aria-label','Copy '+link.label);row.append(url,copy);list.append(label,row);}
 if(!links.length)list.append(el('p','Stream addresses have not been received from StreamHub yet.'));
 if(item.servesStreamLinks&&!links.some(x=>x.label.startsWith('Public')))list.append(el('p','Public addresses require the signed-in StreamHub GUI session on this server.'));

}
async function openInputSources(i){const {d,list}=picker(`Input ${i.id} · Existing sources`);try{const catalog=await call({type:'presets'});for(const p of catalog.inputs){const b=button(p.name||`Profile ${p.id}`,async()=>{d.close();d.remove();await runAction(async()=>{const r=await write({type:'assignPreset',input:i.id,preset:p.id});update(r.snapshot);note('Source assignment confirmed.');},'IN:'+i.id);});b.disabled=p.assigned;list.append(b);}if(!catalog.inputs.length)list.append(el('p','No existing IP profiles. Create profiles in StreamHub.'));}catch(e){list.append(el('p',e.message));}}
const outputAdds=new Map();
function renderOutputAdds(grid){
 const desired=[];
 for(const type of ['SDI','NDI','IP']){
  for(const i of data.outputs.filter(o=>o.type===type))desired.push(cards.get(i.key).card);
  let add=outputAdds.get(type);if(!add){add=button('+',()=>addCategoryOutput(type),'output-add-tile');add.dataset.outputGroup=type;add.setAttribute('aria-label','Add existing '+type+' output');outputAdds.set(type,add);}
  const available=(data.outputProfiles||[]).filter(p=>p.type===type&&!p.present&&!p.locked&&(p.canAdd!==false));
  if(type==='SDI'&&!available.length){add.remove();continue;}
  add.disabled=busy||!online||!available.length;add.title=available.length?'Add existing '+type+' output':'No available '+type+' outputs reported by StreamHub';
  add.replaceChildren(el('span',type,'output-add-label'),el('span','+','output-add-symbol'));desired.push(add);
 }
 desired.forEach((node,n)=>{if(grid.children[n]!==node)grid.insertBefore(node,grid.children[n]||null);});
}
async function addCategoryOutput(type){if(type==='IP'){openOutputs(type);return;}const p=(data.outputProfiles||[]).filter(p=>p.type===type&&!p.present&&!p.locked&&p.canAdd!==false).sort((a,b)=>Number(a.index)-Number(b.index))[0];if(p)await addExistingOutput(p);}
async function addExistingOutput(p){await runAction(async()=>{const r=await write({type:'outputAdd',key:p.key});update(r.snapshot);note('Existing output added.');},p.key);}
function openOutputSources(output){const {d,list}=picker(`${output.name} · Input source`);const inputs=data.inputs.filter(i=>i.connected||i.protocolId>=0);for(const input of inputs){const b=button(`Input ${input.id} · ${input.name}`,async()=>{d.close();d.remove();await runAction(async()=>{const r=await write({type:'route',input:input.id,keys:[output.key]});update(r.snapshot);note(r.results.map(x=>x.message).join(' · '));},output.key);});b.disabled=busy||!online||output.locked;list.append(b);}appendOutputEncoders(output,list,d);if(!inputs.length&&!nativeState.encoders.length)list.append(el('p','No assigned or connected inputs available.'));}
async function openOutputs(type){const {d,list}=picker('Add an existing '+(type||'')+' output');const profiles=(data.outputProfiles||[]).filter(p=>!p.present&&(!type||p.type===type));for(const p of profiles){const b=button(`${p.name} · ${p.type==='IP'?p.mode:p.type}`,async()=>{d.close();d.remove();await runAction(async()=>{const r=await write({type:'outputAdd',key:p.key});update(r.snapshot);note('Existing output added.');},p.key);});b.disabled=p.locked||p.canAdd===false;if(p.addHint)b.title=p.addHint;list.append(b);}if(!profiles.length)list.append(el('p','No unused output profiles reported. Create profiles in StreamHub.'));}

function terminalRecord(i){if(typeof i.deviceRecording==='boolean'){inputAction(i,'inputControl',i.deviceRecording?'stop':'start','record');return;}const d=el('dialog');d.append(el('h2','Terminal recording'),el('p','The API does not report terminal recording state. Send an explicit command.'));for(const action of ['start','stop'])d.append(button(action==='start'?'Start recording':'Stop recording',async()=>{d.close();d.remove();await inputAction(i,'inputControl',action,'record');}));d.append(button('Close',()=>{d.close();d.remove();}));document.body.append(d);d.showModal();}
async function waitCameraIdle(){stopRockers();clearTimeout(commandTimer);while(pending.size||cameraSending){if(!cameraSending)await flushCamera();else await new Promise(r=>setTimeout(r,30));}}
async function runAction(fn,key){if(!online||locks.has(key)||busy)return;locks.add(key);render();try{await waitCameraIdle();await fn();}catch(e){note(e.message);}finally{locks.delete(key);render();}}
async function inputAction(item,type,action,endpoint){await runAction(async()=>{const d=await write({type,input:item.id,action,endpoint});if(d.snapshot)update(d.snapshot);note(`${item.name}: ${action} command accepted.`);},'IN:'+item.id);await refresh();}
async function discoverMojo(){if(discovering||!connected||locks.size||cameraSending||pending.size||anyHeld())return;discovering=true;const e=epoch;render();try{const d=await call({type:'mojoDiscover'});if(e!==epoch)return;mojoInputs=d.inputs;for(const i of mojoInputs){const row=data.inputs.find(x=>x.id===i.id);if(row)row.isMojo=true;}}catch(err){note(err.message);}finally{discovering=false;render();}}
let navigating=false;
async function navigateMojo(direction){if(navigating||busy||!online||!mojo)return;const list=[...mojoInputs].filter(i=>i.connected).sort((a,b)=>a.id-b.id),index=list.findIndex(i=>i.id===mojo.input);if(index<0||list.length<2)return;const target=list[(index+direction+list.length)%list.length];navigating=true;render();try{await openMojo(target);}finally{navigating=false;render();}}
async function openMojo(item){await waitCameraIdle();if(mojo)mojoStates.set(mojo.deviceUID,mojo);tab='mojo';versions.clear();sentAt.clear();acknowledged.clear();tab='mojo';const saved=mojoStates.get(item.uid);if(saved){mojo=saved;syncCamera();render();}await readMojo(item.id,item.name);}
async function readMojo(id,name){if(!online)return;await waitCameraIdle();const e=epoch;try{note(`Reading ${name}…`);const d=await call({type:'mojoGet',input:id});if(e!==epoch)return;mojo={...d,input:id,name};mojoStates.set(d.deviceUID,mojo);stepRemainder.clear();for(const k of Object.keys(profiles))acknowledged.set(k,structuredClone(d.settings[k]));syncCamera();render();requestPreviewNow();note(d.readError|| (d.partial?'Some camera values are not returned by StreamHub.':'Camera state read.'));}catch(e){note(e.message);}}
const stepRemainder=new Map();
const profiles={WB:{name:'White balance',digits:0},ISO:{name:'ISO',digits:0},ShutterSpeed:{name:'Shutter',digits:0},Focus:{name:'Focus',digits:3},Zoom:{name:'Zoom',digits:3},AudioGain:{name:'Audio gain',digits:2}};
function setPosition(group,t){
 if(!mojo||!online||busy)return;const native=mojo.settings[group],range=RCP.bounds(group,native,mojo.profile);if(!range||!Number.isFinite(range[1]))return;
 const shutterSteps=group==='ShutterSpeed'?RCP.shutterSteps(native,mojo.profile):[];const value=group==='ShutterSpeed'?shutterSteps[Math.round(t*(shutterSteps.length-1))]:['ISO','Zoom'].includes(group)?range[0]*Math.pow(range[1]/range[0],t):range[0]+t*(range[1]-range[0]);const patch={[group]:RCP.toApi(group,value,mojo.profile)},key=group+'Mode';if(native[group+'Modes']?.includes('OFF'))patch[key]='OFF';enqueueCamera(group,patch);
}
function enqueueCamera(group,patch){if(!mojo||!online||busy)return;if(Object.entries(patch).every(([key,value])=>mojo.settings[group][key]===value))return;const range=mojo.settings[group][group+'Range'],value=patch[group];if(value!==undefined&&(!Number.isFinite(value)||Array.isArray(range)&&(value<range[0]||value>range[1])||group==='Zoom'&&value<1)){note('Value outside the available range.');return;}Object.assign(mojo.settings[group],patch);mojo.reported[group]=false;mojo.origin[group]='command';pendingTarget={input:mojo.input,epoch};pending.set(group,{...(pending.get(group)||{}),...patch});versions.set(group,(versions.get(group)||0)+1);syncControl(group,true);if(commandTimer===null&&!cameraSending)commandTimer=setTimeout(flushCamera,80);}
async function flushCamera(){clearTimeout(commandTimer);commandTimer=null;if(cameraSending||!pending.size)return;const target=pendingTarget,patch=Object.fromEntries(pending),revision=new Map(versions);pending.clear();cameraSending=true;for(const k of Object.keys(patch))controls.get(k)?.card.setAttribute('data-pending','true');try{const d=await write({type:'mojoSet',input:target.input,patch});if(target.epoch===epoch&&mojo?.input===target.input){for(const k of Object.keys(patch)){sentAt.set(k,Date.now());if(d.settings?.[k])acknowledged.set(k,{...mojo.settings[k],...d.settings[k]});if(versions.get(k)===revision.get(k)&&d.settings?.[k])Object.assign(mojo.settings[k],d.settings[k]);syncControl(k,true);}note('Camera command accepted.');}}catch(e){stopRockers();pending.clear();stepRemainder.clear();clearTimeout(commandTimer);if(mojo?.input===target.input)for(const k of Object.keys(patch)){if(acknowledged.has(k))mojo.settings[k]=structuredClone(acknowledged.get(k));syncControl(k,true);}note(e.message);}finally{cameraSending=false;if(!pending.size)for(const c of controls.values())c.card.dataset.pending='false';if(pending.size)commandTimer=setTimeout(flushCamera,50);}}
function buildCamera(){
 stopRockers();controls.clear();const host=$('#camera');host.replaceChildren();const console=el('div',undefined,'rcp-console'),top=el('div',undefined,'rcp-top'),brand=el('div',`${mojo.name} · StreamHub Input ${mojo.input}`,'rcp-brand'),choices=el('div',undefined,'camera-choice'),speeds=el('div',undefined,'rcp-speed');top.append(brand,choices,speeds);if(typeof attachMojoPreview==='function')attachMojoPreview(top);console.classList.toggle('no-focus',!mojo.focusAvailable);console.append(top);const grid=el('div',undefined,'rcp-bank');
 for(const [group,p] of Object.entries(profiles)){if(group==='Focus'&&!mojo.focusAvailable)continue;const card=el('div',undefined,'rcp-channel');card.dataset.control=group;card.dataset.section=['WB','ISO','ShutterSpeed'].includes(group)?'exposure':'lens';const header=el('div',undefined,'rcp-channel-head'),label=el('h3',group==='WB'?'WHITE BALANCE':p.name.toUpperCase()),lamp=el('span',undefined,'readback-lamp');header.append(label,lamp);card.append(header);
 const display=el('div',undefined,'rcp-display'),readout=el('input',undefined,'readout'),unit=el('span',group==='WB'?'K':group==='ISO'?'ISO':group==='ShutterSpeed'?'s':group==='Zoom'?'×':group==='AudioGain'?'dB':'','rcp-unit');readout.type='text';readout.inputMode=group==='ShutterSpeed'?'text':'decimal';readout.setAttribute('aria-label',p.name);display.append(readout,unit);card.append(display);
 const mode=['WB','ISO','ShutterSpeed','Focus'].includes(group)?el('button','AUTO','auto-key'):null;if(mode){mode.onclick=()=>{const key=group+'Mode',s=mojo.settings[group];enqueueCamera(group,{[key]:s[key]==='AUTO'?'OFF':'AUTO'});};card.append(mode);}else card.append(el('div',undefined,'auto-spacer'));
 const rocker=createEncoder({label:p.name,vertical:group==='Zoom',onValue:t=>setPosition(group,t),onRelease:()=>{if(pending.size&&!cameraSending){clearTimeout(commandTimer);commandTimer=setTimeout(flushCamera,0);}}});card.append(rocker.element);readout.onchange=()=>{try{const displayed=RCP.parse(group,readout.value),range=RCP.bounds(group,mojo.settings[group],mojo.profile);if(!Number.isFinite(displayed)||!range||displayed<range[0]||displayed>range[1])throw Error('Value outside the available device range.');const steps=group==='ShutterSpeed'?RCP.shutterSteps(mojo.settings[group],mojo.profile):[];const snapped=group==='ShutterSpeed'?steps[RCP.shutterIndex(displayed,mojo.settings[group],mojo.profile)]:displayed;const patch={[group]:RCP.toApi(group,snapped,mojo.profile)},key=group+'Mode';if(mojo.settings[group][group+'Modes']?.includes('OFF'))patch[key]='OFF';enqueueCamera(group,patch);}catch(e){note(e.message);syncControl(group,true);}};readout.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();readout.onchange();readout.blur();}};controls.set(group,{card,readout,mode,rocker,lamp});grid.append(card);
 }console.append(grid);host.append(console);cameraView=[mojo.input,mojo.deviceUID,mojo.settings.camera,!!mojo.focusAvailable].join('|');
}
function syncControl(group,local=false){const c=controls.get(group),s=mojo?.settings[group];if(!c||!s)return;const value=RCP.fromApi(group,s[group],mojo.profile);if(local||document.activeElement!==c.readout){const formatted=RCP.format(group,value);if(c.readout.value!==formatted)c.readout.value=formatted;}c.lamp.dataset.origin=mojo.reported[group]?'device':Number.isFinite(s[group])?'command':'unknown';c.lamp.title=c.lamp.dataset.origin==='device'?'Device readback':c.lamp.dataset.origin==='command'?'Last sent command · not device confirmation':'No value returned by StreamHub';if(c.mode){text(c.mode,s[group+'Mode']==='AUTO'?'AUTO':'MANUAL');c.mode.classList.toggle('active',s[group+'Mode']==='AUTO');c.mode.disabled=!online||busy||!s[group+'Modes']?.includes('OFF')||!s[group+'Modes']?.includes('AUTO');}c.readout.title=group==='WB'?'1500–10000 K':group==='ISO'?'100–6400':group==='ShutterSpeed'?'1/25600–1/25 second':'Enter a value';const bounds=RCP.bounds(group,s,mojo.profile);const numericAvailable=!!bounds&&Number.isFinite(bounds[1])&&(group!=='ShutterSpeed'||RCP.shutterSteps(s,mojo.profile).length>0);c.readout.disabled=!online||busy||!numericAvailable;c.rocker.setEnabled(online&&!busy&&numericAvailable);c.rocker.element.title=numericAvailable?'':group==='ShutterSpeed'&&!mojo.profile.shutterUnit?'Shutter API units are not established for this camera.':'Numeric control range unavailable.';const steps=group==='ShutterSpeed'?RCP.shutterSteps(s,mojo.profile):[];c.rocker.setSteps(steps.length||null);if(bounds&&Number.isFinite(bounds[1])&&value!==null)c.rocker.setValue(group==='ShutterSpeed'?RCP.shutterIndex(value,s,mojo.profile)/Math.max(1,steps.length-1):['ISO','Zoom'].includes(group)?Math.log(value/bounds[0])/Math.log(bounds[1]/bounds[0]):(value-bounds[0])/(bounds[1]-bounds[0]));}
function syncCamera(){if(!mojo)return;if(cameraView!==[mojo.input,mojo.deviceUID,mojo.settings.camera,!!mojo.focusAvailable].join('|'))buildCamera();if(typeof syncMojoPreview==='function')syncMojoPreview();const choices=$('#camera .camera-choice'),names=mojo.cameras.names,signature=JSON.stringify(names);if(choices.dataset.names!==signature){choices.replaceChildren(...names.map(name=>button(name,()=>setCamera(name))));choices.dataset.names=signature;}for(const b of choices.querySelectorAll('button'))b.classList.toggle('active',b.textContent===mojo.settings.camera);for(const k of Object.keys(profiles))syncControl(k);}
async function setCamera(name){if(busy||!mojo)return;await waitCameraIdle();const id=mojo.input,uid=mojo.deviceUID,e=epoch;busy=true;render();try{const d=await write({type:'mojoSet',input:id,camera:name});if(e!==epoch||mojo?.deviceUID!==uid||mojo?.input!==id)return;mojo={...d,input:id,name:mojo.name};mojoStates.set(uid,mojo);versions.clear();sentAt.clear();acknowledged.clear();stepRemainder.clear();for(const k of Object.keys(profiles))acknowledged.set(k,structuredClone(d.settings[k]));cameraView='';syncCamera();note('Selected camera state confirmed by StreamHub.');}catch(e){note(e.message);if(mojo?.input===id){mojo.focusAvailable=false;mojo.settings.Focus={};cameraView='';syncCamera();}}finally{busy=false;render();requestPreviewNow();}}
async function refresh(manual=false){if(!connected||busy||locks.size||polling||!visible||cameraSending||pending.size||anyHeld())return;polling=true;const e=epoch;try{const d=await call({type:'snapshot'});if(e!==epoch)return;update(d);online=true;const signature=d.inputs.filter(i=>i.connected).map(i=>i.id+':'+i.uid+':'+i.product).join('|');if(signature!==deviceSignature){deviceSignature=signature;discoverMojo();}if(manual)note('Status refreshed.');}catch(err){if(e===epoch){online=false;note(err.message);}}finally{polling=false;render();}}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>switchTab(b.dataset.tab);
$('form').onsubmit=async e=>{e.preventDefault();if(busy)return;try{const t=$('#address').value.trim(),u=new URL(/^https?:\/\//i.test(t)?t:'http://'+t);if(!['http:','https:'].includes(u.protocol)||u.pathname!=='/'||u.username||u.password||u.search||u.hash)throw Error('Enter only an IP address or hostname, optionally with a port.');if(!u.port)u.port=u.protocol==='https:'?'8896':'8893';if(!await chrome.permissions.request({origins:[u.origin+'/*']}))throw Error('Host access was not granted.');busy=true;render();note('Connecting…');const d=await write({type:'connect',address:u.origin,key:$('#key').value});epoch++;connected=online=true;base=d.base;update(d.snapshot);$('#key').value='';note('Connected.');discoverMojo();}catch(e){note(e.message);}finally{busy=false;render();}};
function reset(){if(typeof clearFeatures==='function')clearFeatures();source=null;selected.clear();gridView='';tab='inputs';if(typeof previewCache!=='undefined')previewCache.clear();epoch++;stopRockers();mojoStates.clear();pending.clear();clearTimeout(commandTimer);commandTimer=null;mojo=null;mojoInputs=[];data={inputs:[],outputs:[]};deviceSignature='';cameraView='';cards.clear();controls.clear();$('#grid').replaceChildren();$('#camera').replaceChildren();}
$('#forget').onclick=async()=>{if(busy)return;await waitCameraIdle();busy=true;try{await write({type:'forget'});reset();connected=online=false;$('#key').value='';note('Connection and API key removed.');}catch(e){note(e.message);}finally{busy=false;render();}};
window.addEventListener('blur',stopRockers);function suspendPanel(){clearFeatures();terminalRecordingStates.clear();stopRockers();clearTimeout(commandTimer);commandTimer=null;pending.clear();stepRemainder.clear();}document.addEventListener('visibilitychange',()=>{if(document.hidden)suspendPanel();else if(visible)refresh();});window.addEventListener('message',e=>{if(e.source===parent&&e.data?.type==='sh-visible'){visible=e.data.visible===true;if(!visible)suspendPanel();else{stopRockers();mojo=null;tab='inputs';source=null;selected.clear();cameraView='';render();refresh();}}});
chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.connection){reset();const c=changes.connection.newValue;connected=!!c?.key;base=c?.base||'';online=false;render();if(connected&&!busy)refresh();}});
registerPoll(refresh,2000);registerPoll(()=>{if(visible&&connected&&!busy)discoverMojo();},15000);let cameraPolling=false;registerPoll(async()=>{if(!visible||!online||busy||locks.size||cameraPolling||cameraSending||pending.size||anyHeld()||tab!=='mojo'||!mojo||document.activeElement?.closest('#camera input,#camera select'))return;const id=mojo.input,e=epoch,revision=new Map(versions);cameraPolling=true;try{const d=await call({type:'mojoGet',input:id});if(e===epoch&&mojo?.input===id&&!busy){for(const k of Object.keys(profiles))if(!anyHeld()&&!cameraSending&&versions.get(k)===revision.get(k)&&!pending.has(k)&&Date.now()-(sentAt.get(k)||0)>2000){mojo.profile=d.profile;mojo.settings[k]=d.settings[k];acknowledged.set(k,structuredClone(d.settings[k]));mojo.reported[k]=d.reported[k];}mojo.known=d.known;mojo.focusAvailable=d.focusAvailable;mojo.origin=d.origin;mojo.partial=d.partial;if(!cameraSending&&!pending.size)mojo.settings.camera=d.settings.camera;syncCamera();}}catch{}finally{cameraPolling=false;}},5000);
(async()=>{try{const s=await call({type:'state'});connected=s.connected;base=s.base||'';render();if(connected){await refresh();note('Connected.');}}catch(e){note(e.message);}})();

