/* StreamHub native English message catalog; preserve server codes and parameters. */
const STREAMHUB_MESSAGES={
 "terminal": {
  "-1": "Unexpected error.",
  "-2": "Configuration error.",
  "-3": "Live not supported by this version.",
  "-4": "Forward not supported by this version.",
  "-5": "Operation denied. Firmware update in progress.",
  "-10": "No destination profile selected.",
  "-11": "Missing username for connecting to StreamHub.",
  "-12": "Missing password for connecting to StreamHub.",
  "-13": "Missing IP address for connecting to StreamHub.",
  "-14": "Destination profile required for Auto-Forward.",
  "-15": "Missing username for connecting to Manager.",
  "-16": "Missing password for connecting to Manager.",
  "-17": "Missing IP address for connecting to Manager.",
  "-19": "There is no valid license.",
  "-20": "No interface connected.",
  "-21": "No Live profile selected.",
  "-22": "Simultaneous Live and Record in H.265/HEVC not supported.",
  "-23": "Live in H.264/AVC not supported.",
  "-24": "Record in H.264/AVC not supported.",
  "-25": "Live and Record in H.264/AVC 1080p50/59.94/60Hz not supported.",
  "-26": "Live in H.265/HEVC not supported.",
  "-27": "Record in H.265/HEVC not supported.",
  "-28": "Too low video bitrate (min. ${param.arg2} kbps for ${param.arg1}).",
  "-29": "Too high video bitrate (max. ${param.arg2} kbps for ${param.arg1}).",
  "-30": "No SD Card detected.",
  "-31": "SD Card is locked.",
  "-32": "SD Card is full.",
  "-33": "Cannot write to SD Card.",
  "-34": "Battery level too low.",
  "-35": "Recorded file too large.",
  "-36": "No Record profile selected.",
  "-37": "Internal temperature is at critical level. Shutting down.",
  "-38": "Record not supported.",
  "-39": "SDI input configuration not supported in multiple cameras mode.",
  "-40": "Bad video synchronisation.",
  "-41": "Video not locked.",
  "-42": "Video input frequency mismatch.",
  "-43": "Video standard not supported.",
  "-44": "Video input is not HD.",
  "-45": "Video standard not supported in multiple cameras mode.",
  "-46": "Missing signal on SDI.",
  "-47": "Video SDI level not supported.",
  "-48": "Missing signal on analog.",
  "-49": "No standard detected on analog.",
  "-50": "Missing cable on HDMI.",
  "-51": "Missing signal on HDMI.",
  "-52": "HDMI input not locked.",
  "-53": "Missing audio signal on HDMI.",
  "-54": "Missing audio signal on SDI.",
  "-55": "Timed out while waiting for an input video stream.",
  "-56": "Timed out while waiting for an input audio stream.",
  "-57": "End-to-end latency too short, check Live profile.",
  "-58": "Video source upscaling not supported.",
  "-59": "Video standard not supported (license required).",
  "-60": "Authentication failed.",
  "-61": "Destination input busy.",
  "-62": "Invalid connection.",
  "-63": "Incompatible destination firmware version.",
  "-64": "Disconnected by Manager.",
  "-65": "Failed to connect.",
  "-66": "Connection lost.",
  "-67": "Failed to connect to Manager.",
  "-68": "Cannot obtain destination profile from Manager.",
  "-69": "Connection rejected by Manager.",
  "-70": "Failed to start Live.",
  "-71": "Failed to start recording.",
  "-72": "Failed to start forwarding.",
  "-73": "Failed to forward the file.",
  "-74": "Failed to forward: Manager error.",
  "-76": "Connection failure: Check Manager credentials.",
  "-80": "Video encoder error.",
  "-81": "Audio encoder error.",
  "-82": "Aux encoder error.",
  "-83": "Video encoder error (reboot required).",
  "-85": "Cannot start action since Data Bridge is on.",
  "-91": "No mass storage or compatible file system detected.",
  "-92": "Error while getting the mass storage listing.",
  "-98": "No file found.",
  "-110": "Unexpected error (internal timeout).",
  "-111": "Unexpected error (connection refused).",
  "-112": "BGAN network registration failed.",
  "-113": "BGAN terminal mismatches configuration.",
  "-114": "BGAN pointing failed.",
  "-115": "BGAN PDP context application failed.",
  "-116": "BGAN QoS profile application failed.",
  "-117": "BGAN network activation failed.",
  "-118": "BGAN network disconnection failed.",
  "-119": "BGAN unexpected error.",
  "-120": "BGAN terminal is unreachable.",
  "-121": "BGAN GPS not locked.",
  "-122": "BGAN not ready.",
  "-123": "No compliant BGAN terminal detected.",
  "-124": "Max connection reached.",
  "-125": "Invalid license.",
  "-126": "Expired license.",
  "-127": "No license found.",
  "-128": "Destination input not supported.",
  "-129": "Max token reached.",
  "-130": "Feature license not present.",
  "-131": "Feature license expired.",
  "-132": "Internal error.",
  "-133": "Live not supported (license required).",
  "-140": "Missing action.",
  "-141": "No StreamHub available.",
  "-142": "Destination input not available.",
  "-143": "Device disabled.",
  "-144": "Reserved destination input is busy.",
  "-145": "Reserved destination input not available.",
  "-146": "Device disconnected.",
  "-147": "Booked StreamHub not available.",
  "-148": "No StreamHub registered on Manager.",
  "-149": "Unexpected error on Manager.",
  "-150": "No story selected.",
  "-151": "StreamHub not allocated.",
  "-160": "AES disabled on Manager.",
  "-161": "AES enabled on Manager.",
  "-162": "Connection not authorized for this product.",
  "-163": "Connection not authorized for this product.",
  "-164": "Server type mismatch. Check your destination profile.",
  "-170": "Same codec required for simultaneous Live and Record.",
  "-171": "Same codec required for all streams.",
  "-172": "Max number of audio channels exceeded.",
  "-173": "UHD Record not supported during UHD Live.",
  "-174": "H.264/AVC UHD not supported.",
  "-175": "Same video standard required for each input.",
  "-176": "No genlock signal.",
  "-177": "Mismatching genlock signal (${param.arg1}).",
  "-178": "Max number of deinterlacers (2) exceeded.",
  "-180": "BGAN not supported in multiple cameras mode.",
  "-181": "BGAN SIM missing.",
  "-182": "BGAN connection mode mismatches configuration.",
  "-190": "Disconnected by StreamHub.",
  "-191": "Disconnected by Haivision Hub 360.",
  "-192": "Failed to connect to Haivision Hub 360.",
  "-193": "Cannot obtain destination profile from Haivision Hub 360.",
  "-194": "Connection rejected by Haivision Hub 360.",
  "-195": "AES disabled on StreamHub.",
  "-196": "AES enabled on StreamHub.",
  "-197": "AES disabled on Haivision Hub 360.",
  "-198": "AES enabled on Haivision Hub 360.",
  "-199": "Connection failure. Check StreamHub credentials.",
  "-200": "Connection failure. Check Haivision Hub 360 credentials.",
  "-201": "No StreamHub registered on Haivision Hub 360.",
  "-202": "No associated output on Haivision Hub 360.",
  "-203": "Failed to connect to Haivision Hub 360 (client internal error).",
  "-204": "Failed to connect to Haivision Hub 360 (authentication server error).",
  "-205": "Failed to connect to Haivision Hub 360 (bad network error).",
  "-206": "Failed to connect to Haivision Hub 360 (authentication error).",
  "-207": "Failed to connect to Haivision Hub 360 (certificate error).",
  "-208": "Failed to connect to Haivision Hub 360 (token error).",
  "-209": "Failed to connect to Haivision Hub 360 (endpoint creation error).",
  "-210": "Failed to connect to Haivision Hub 360 (access disabled).",
  "-211": "Failed to connect to Haivision Hub 360 (align device and Hub dates).",
  "-212": "Failed to connect to Haivision Hub 360 (no network interface connected).",
  "-213": "Failed to connect to Haivision Hub 360 (client unknown error).",
  "-214": "Unexpected error on Haivision Hub 360.",
  "-215": "Failed to pair to Haivision Hub 360 (maximum number of paired appliances reached).",
  "-220": "Low latency transmission not supported in multiple cameras mode.",
  "-221": "Auto-record not supported during low latency Live.",
  "-222": "Record not supported during low latency Live.",
  "-223": "Latency not supported for this video standard (min. ${param.arg1} ms).",
  "-230": "Live and Destination profiles mismatch for SRT.",
  "-231": "No Ethernet connected.",
  "-232": "SRT authentication failed.",
  "-233": "Same SRT port and IP address used in multiple Destination profiles.",
  "-234": "Invalid IP/hostname in Destination profile.",
  "-235": "Recorded file doesn't exist.",
  "-236": "Audio must be 1 x MONO or 1 x STEREO.",
  "-237": "Invalid Ethernet port in Destination profile.",
  "-238": "Cannot write to internal storage.",
  "-239": "Internal storage is full.",
  "-240": "Unexpected auto-reconfiguration error.",
  "-241": "Invalid auto-reconfiguration file.",
  "-242": "Unexpected product in auto-reconfiguration file.",
  "-243": "Live stopped due to the absence of video source.",
  "-244": "Live and auto-record stopped due to the absence of video source.",
  "UNKNOWN_CODE": "Unknown error (${param.code})."
 },
 "input": {
  "No connection": "No connection",
  "Device ready": "Device ready",
  "Checking environnement ...": "Checking environnement",
  "Checking video ...": "Checking video",
  "Connection in progress ...": "Connection in progress ...",
  "Bandwidth test in progress ...": "Bandwidth test in progress ...",
  "Live and Record in progress ...": "Live and Record in progress ...",
  "Live and Record in progress  (No Video Input)...": "Live and Record in progress  (No Video Input)...",
  "Live in progress ...": "Live in progress ...",
  "Live in progress (No Video Input)...": "Live in progress (No Video Input)...",
  "Live with Data Hotspot in progress ...": "Live with DataBridge in progress ...",
  "Live and Record with Data Hotspot in progress ...": "Live and Record with DataBridge in progress ...",
  "Record and Forward in progress ...": "Record and Forward in progress ...",
  "Forward in progress ...": "Forward in progress ...",
  "Record in progress ...": "Record in progress ...",
  "Hotspot enabled": "Hotspot enabled",
  "NOT_FOUND": "Not found",
  "FAILED_TO_CONNECT": "Failed to connect",
  "FAILED_TO_OPEN_FILE": "Failed to open file",
  "READ_FROM": "Read error",
  "WRITE_TO": "Write error",
  "NOT_SUPPORTED": "Not supported",
  "SETTINGS": "Settings error",
  "INTERNAL": "Internal error",
  "LOST_INPUT": "Lost input",
  "CONNECTION_LOST": "Connection lost",
  "STREAM_LOST": "Stream lost",
  "SOURCE_NOT_STREAMING": "Source not streaming",
  "UNKNOWN": "Unknown error",
  "CODEC_NOT_SUPPORTED": "Codec not supported",
  "RESOLUTION_NOT_SUPPORTED": "Resolution not supported",
  "STREAM_NOT_SUPPORTED": "Stream's format not supported",
  "DECODING_NOT_REALTIME": "Real-time decoding error due to hardware limitation",
  "MISSING_AUDIO_SRC": "Missing audio source",
  "MISSING_VIDEO_SRC": "Missing video source",
  "ENCODER_VIDEO_UNDEFINED": "Encoder video undefined",
  "ENCODER_AUDIO_UNDEFINED": "Encoder audio undefined",
  "Guest is prepared": "Guest is prepared",
  "Guest is live": "Guest is live",
  "Guest hung up": "Guest hung up",
  "NOT_SUPPORTED_WITH_INPUT_ULL": "Not supported with ULL",
  "RECORD_NOT_SUPPORTED_WITH_INPUT_ULL": "Recorder not supported with ULL"
 },
 "output": {
  "SRC_MISSING": "Source missing",
  "SRC_DEAD": "Source dead",
  "DST_BAD": "Bad destination",
  "DST_BAD_OR_CREDENTIAL": "Bad destination or credentials",
  "OVERRUN": "Overrun error",
  "INTERNAL": "Internal error",
  "STREAM_CORRUPT": "Stream error",
  "BAD_NETWORK": "Bad network",
  "CLOSE_BY_PEER": "Connection reset by peer",
  "IMPROPER_URI": "Improper URL",
  "DNS_ISSUE": "DNS issue",
  "HOST_UNREACHABLE": "Host unreachable",
  "CONNECTION_REFUSED": "Connection refused",
  "CONNECTION_TIMEDOUT": "Connection timed out",
  "RTMP_HANDSHAKE": "Not RTMP server",
  "RTMP_STREAMCONNECTION": "RTMP stream refused",
  "RTMP_LOSTCONNECTION": "Connection lost",
  "CODEC_NOT_SUPPORTED": "Codec not supported",
  "AUDIO_MODE_NOT_SUPPORTED": "Only one audio track supported",
  "UNKNOWN": "Unknown error",
  "BAD_AUTHENTIFICATION": "Authentication error",
  "NEED_AUTHENTIFICATION": "Authentication needed",
  "CONNECTION_LOST": "Connection lost",
  "CHANNEL_BUSY": "Input is busy",
  "LICENSE_NOT_VALID": "License not valid",
  "NO_MORE_LICENSE_AVAILABLE": "No more license available",
  "DEVICE_DISABLED_BY_MANAGER": "Device disabled by Manager",
  "LICENSE_EXPIRED": "License expired",
  "LICENSE_NOT_FOUND": "License not found",
  "AES_SERVER_DISABLED": "AES Server disabled",
  "CHANNEL_DISABLED": "Input is disabled",
  "DEVICE_CONNECTION_NOT_AUTHORIZED": "Device connection not authorized",
  "OUTPUT_DELAY_TOO_LOW": "Output latency too low",
  "TS_CBR_OUTPUT_DROP": "Output TS bitrate too low",
  "BAD_PICTURE": "Pattern format not supported",
  "SMPTE_2110_BAD_LICENSE": "License SMPTE2110 not valid",
  "DECODING_NOT_REALTIME": "Real-time decoding error due to hardware limitation",
  "NO_MULTI_OUTPUT_WITH_INPUT_ULL": "No multiple outputs with ULL",
  "NOT_SUPPORTED_WITH_INPUT_ULL": "Not supported with ULL"
 }
};
function terminalDiagnosticFields(r){const code=['liveStatus','IAPStatus','recordStatus','forwardStatus'].map(k=>Number(r[k])).find(v=>v<0)||0;let args=[];for(const k of ['liveStatusErrorParam','recordStatusErrorParam'])if(typeof r[k]==='string'&&r[k])args=r[k].split(';');return {message:typeof r.message==='string'?r.message:'',errorCode:code,errorParams:{'param.arg1':args[0]||'720p50','param.arg2':args[1]||'20'}};}
function streamHubDiagnostic(item,kind='input',native=null){
 if(!item)return null;
 const row=kind==='input'&&native?{...item,...native}:item,status=Number(row.status);
 if(![3,4].includes(status)||(kind==='output'&&!row.enabled))return null;
 const severity=status===3?'error':'warning',fallback=status===3?'Error':'Warning',raw=typeof row.message==='string'?row.message:'';
 const catalog=kind==='output'?STREAMHUB_MESSAGES.output:STREAMHUB_MESSAGES.input;
 let message=kind==='input'&&Number(row.errorCode)<0?STREAMHUB_MESSAGES.terminal[row.errorCode]||raw:catalog[raw]||raw;
 if(message)message=message.replace(/\$\{([^}]+)\}/g,(match,key)=>row.errorParams?.[key]??match);
 return {severity,message:message||fallback};
}
function paintDiagnostic(c,item,kind='input'){
 if(!c.diagnostic)return;
 const diagnostic=online?streamHubDiagnostic(item,kind,kind==='input'&&typeof nativeInput==='function'?nativeInput(item):null):null;
 c.diagnostic.hidden=!diagnostic;c.preview.dataset.diagnostic=diagnostic?.severity||'';
 text(c.diagnostic,diagnostic?.message||'');c.diagnostic.title=diagnostic?.message||'';
 if(c.state){c.state.classList.toggle('error',diagnostic?.severity==='error');c.state.classList.toggle('warning',diagnostic?.severity==='warning');if(diagnostic){text(c.state,diagnostic.severity.toUpperCase());c.state.classList.remove('live');}}
}
