/* Absolute bounded controls: lower-left to lower-right over a 270 degree arc. */
window.createEncoder=function({label,vertical=false,onValue,onRelease}){
 const row=document.createElement('div');row.className=vertical?'rcp-row zoom-row':'rcp-row encoder-row';
 const dial=document.createElement('div');dial.className=vertical?'zoom-fader':'encoder';dial.tabIndex=0;dial.setAttribute('role','slider');dial.setAttribute('aria-label',label);dial.setAttribute('aria-valuemin','0');dial.setAttribute('aria-valuemax','100');dial.setAttribute('aria-orientation',vertical?'vertical':'horizontal');dial.innerHTML=vertical?'<i class="fader-cap"></i>':'<div class="encoder-cap"><i></i></div>';row.append(dial);
 let pointer=null,value=0,enabled=false,lastAngle=null,stepCount=null;
 const snapped=()=>stepCount?Math.round(value*(stepCount-1))/(stepCount-1):value;function paint(){const displayed=snapped();dial.setAttribute('aria-valuenow',String(Math.round(displayed*100)));if(vertical)dial.firstElementChild.style.bottom=`calc(12px + ${displayed} * (100% - 48px))`;else dial.firstElementChild.style.transform=`rotate(${-135+displayed*270}deg)`;}
 function move(e){const r=dial.getBoundingClientRect();let next;if(vertical)next=1-(e.clientY-r.top-24)/Math.max(1,r.height-48);else{const angle=Math.atan2(e.clientX-r.left-r.width/2,-(e.clientY-r.top-r.height/2))*180/Math.PI;if(lastAngle===null)next=(Math.max(-135,Math.min(135,angle))+135)/270;else{let delta=angle-lastAngle;if(delta>180)delta-=360;if(delta< -180)delta+=360;next=value+delta/270;}lastAngle=angle;}value=Math.max(0,Math.min(1,next));paint();onValue(snapped());}
 dial.onpointerdown=e=>{if(!enabled||e.button!==0)return;e.preventDefault();pointer=e.pointerId;lastAngle=null;dial.setPointerCapture(pointer);move(e);};dial.onpointermove=e=>{if(pointer===e.pointerId)move(e);};
 const stop=()=>{if(pointer===null)return;pointer=null;lastAngle=null;onRelease?.();};dial.onpointerup=dial.onpointercancel=dial.onlostpointercapture=stop;
 dial.onkeydown=e=>{if(!enabled)return;const step=stepCount?1/(stepCount-1):.01,delta={ArrowUp:step,ArrowRight:step,ArrowDown:-step,ArrowLeft:-step};if(stepCount)value=snapped();if(e.key in delta||e.key==='Home'||e.key==='End'){e.preventDefault();value=e.key==='Home'?0:e.key==='End'?1:Math.max(0,Math.min(1,value+delta[e.key]));paint();onValue(snapped());onRelease?.();}};
 paint();return {element:row,stop,setSteps(n){stepCount=n>1?n:null;paint();},setEnabled(v){enabled=v;dial.setAttribute('aria-disabled',String(!v));if(!v)stop();},setValue(v){if(pointer===null){value=Math.max(0,Math.min(1,v));paint();}},get active(){return pointer!==null;}};
};
