/* Direct intercom/return controls and native encoder dashboard. */
let nativeState={ready:false,inputs:[],encoders:[],encoderProfiles:[]},nativeBase='',returnDialog=null,nativeSerial=0;const nativeJobs=new Map();
function nativeCall(command){if(!pollingAllowed()||!online)return Promise.reject(Error('Panel is hidden or disconnected.'));const id='cmd-'+(++nativeSerial);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{nativeJobs.delete(id);reject(Error('Native connection unavailable or command unconfirmed. Open the signed-in StreamHub page.'));},command.action==='encoderEject'?40000:10000);nativeJobs.set(id,{resolve,reject,timer,base});parent.postMessage({type:'sh-native-command',base,id,...command},'*');});}
function nativeInput(i){const row=nativeBase===base?nativeState.inputs.find(r=>r.id===i.id&&r.uid===i.uid):null;return row||null;}
window.addEventListener('message',e=>{if(e.source!==parent||e.data?.base!==base||!pollingAllowed())return;const m=e.data;if(m.type==='sh-native-features'){nativeBase=base;nativeState=m.state;render();syncMojoPreview();}else if(m.type==='sh-native-command-result'){const p=nativeJobs.get(m.id);if(!p||p.base!==base)return;clearTimeout(p.timer);nativeJobs.delete(m.id);m.ok?p.resolve():p.reject(Error(m.error||'Native command rejected.'));}else if(m.type==='sh-native-encoder-preview'){const c=cards.get('ENC:'+m.id);if(c&&typeof m.thumbnail==='string'&&/^data:image\/jpeg;base64,[A-Za-z0-9+/=\r\n]+$/.test(m.thumbnail)){c.image.src=m.thumbnail;c.image.hidden=false;c.previewLabel.hidden=true;c.image.dataset.time=String(Date.now());}}});
function clearFeatures(){if(returnDialog){returnDialog.d.close();returnDialog.d.remove();returnDialog=null;}nativeState={ready:false,inputs:[],encoders:[],encoderProfiles:[]};nativeBase='';for(const p of nativeJobs.values()){clearTimeout(p.timer);p.reject(Error('Panel closed before confirmation.'));}nativeJobs.clear();}
async function nativeAction(command,key='native'){await runAction(async()=>{const block=command.action!=='intercom';if(block){busy=true;render();}try{await nativeCall(command);note(command.action==='intercom'?'Intercom command sent. Waiting for StreamHub state.':command.action==='return'?'Video return assignment confirmed by StreamHub. Check reception on the terminal.':'StreamHub confirmed the change.');}finally{if(block)busy=false;}},key);await refresh();}
function renderEncoderGrid(grid){if(gridView!=='encoders'){cards.clear();grid.replaceChildren();gridView='encoders';}const rows=nativeBase===base?nativeState.encoders.filter(e=>e.profile!=='-1'):[],keys=new Set(rows.map(r=>'ENC:'+r.id));for(const [key,c]of cards)if(!keys.has(key)){c.card.remove();cards.delete(key);}grid.querySelector('.empty')?.remove();for(const [position,e] of rows.entries()){const key='ENC:'+e.id;let c=cards.get(key);if(!c){const card=el('article',undefined,'tile encoder-tile'),head=el('div',undefined,'tile-main'),tagline=el('div',undefined,'tagline'),tag=el('span','Encoder '+e.id),state=el('span',undefined,'state'),name=el('h3',undefined,'name'),sourceButton=button('Input',()=>pickEncoderInput(c.item),'source-select'),bar=el('div',undefined,'tile-controls'),profileButton=icon('eject','EJECT'),power=icon('power','ON');tagline.append(tag,state);head.append(tagline,name);card.append(head,sourceButton,bar);power.onclick=()=>nativeAction({action:'encoderPower',encoder:c.item.id,enabled:!c.item.enabled},key);profileButton.onclick=()=>nativeAction({action:'encoderEject',encoder:c.item.id},key);bar.append(power,profileButton);c={card,head,state,name,sourceButton,profileButton,power,item:e,...makePreview(head,name)};cards.set(key,c);grid.append(card);}if(grid.children[position]!==c.card)grid.insertBefore(c.card,grid.children[position]||null);c.item=e;text(c.name,e.name);text(c.state,e.status===null?(e.enabled?'ON configured':'OFF configured'):['OFF','ON','LIVE','ERROR','WARNING'][e.status]||'UNKNOWN');c.state.classList.toggle('live',e.status===2);text(c.sourceButton,e.input?`Input ${e.input} · ${data.inputs.find(i=>i.id===e.input)?.name||''}`:'Select input');text(c.power.querySelector('span'),e.enabled?'ON':'OFF');c.power.classList.toggle('on',e.enabled);c.power.disabled=busy||!online||locks.has(key)||e.profile==='-1';c.profileButton.disabled=busy||!online||locks.has(key);c.sourceButton.disabled=busy||!online||locks.has(key)||e.profile==='-1';text(c.format,[e.videoReturn?'Video return':'',e.outputInfo].filter(Boolean).join(' · '));if(!e.enabled||Date.now()-Number(c.image.dataset.time||0)>7000){c.image.hidden=true;c.image.removeAttribute('src');c.previewLabel.hidden=false;text(c.previewLabel,!e.enabled?'Encoder OFF':'Waiting for encoder preview…');}paintDiagnostic(c,e,'encoder');}
 const free=nativeBase===base?nativeState.encoders.filter(e=>e.profile==='-1').sort((a,b)=>a.id-b.id):[];if(free.length){let plus=grid.querySelector('.encoder-add-tile');if(!plus){plus=button('',()=>{},'output-add-tile encoder-add-tile');plus.append(el('span','Encoder','output-add-label'),el('span','+','output-add-symbol'));grid.append(plus);}grid.append(plus);plus.onclick=()=>pickEncoderProfile(free[0],true);plus.disabled=busy||!online;plus.title='Add the next available encoder';}else grid.querySelector('.encoder-add-tile')?.remove();
 if(!rows.length&&!free.length)grid.append(el('div',nativeState.ready?'No licensed encoders reported by StreamHub.':'Open the signed-in StreamHub page to read its encoders.','empty'));
}
function pickEncoderProfile(e,add=false){const {d,list}=picker('Encoder '+e.id+' · Existing profiles');for(const p of nativeState.encoderProfiles){const b=button(`${p.name} · ${p.videoReturn?'Video return':p.video||'Encoder'}`,()=>{d.close();d.remove();nativeAction({action:add?'encoderAdd':'encoderProfile',encoder:e.id,profile:p.id},'ENC:'+e.id);});b.disabled=e.enabled;list.append(b);}if(!nativeState.encoderProfiles.length)list.append(el('p','Configure encoder profiles in StreamHub.'));}
function pickEncoderInput(e){const {d,list}=picker('Encoder '+e.id+' · Input');for(const i of data.inputs.filter(i=>i.connected)){list.append(button(`Input ${i.id} · ${i.name}`,()=>{d.close();d.remove();nativeAction({action:'encoderInput',encoder:e.id,input:i.id},'ENC:'+e.id);}));}}
function appendOutputEncoders(output,list,d){if(output.type!=='IP'||nativeBase!==base)return;for(const e of nativeState.encoders.filter(e=>e.profile!=='-1'))list.append(button(`Encoder ${e.id} · ${e.name}`,()=>{d.close();d.remove();nativeAction({action:'outputEncoder',output:String(output.configIndex),encoder:e.id},output.key);}));}

function syncNativeButtons(c,i,unavailable){if(!c.intercom)return;const s=nativeInput(i),terminal=i.connected&&i.canLive;c.unitControls.hidden=!terminal;c.intercom.hidden=!s?.intercomAvailable;c.intercom.disabled=unavailable||!s?.intercomAvailable||typeof s.intercom!=='boolean';c.intercom.classList.toggle('on',s?.intercom===true);c.intercom.setAttribute('aria-pressed',String(s?.intercom===true));c.intercom.title=s?.intercomBusy?'Intercom starting — click to stop':s?.intercom?'Intercom ON — click to stop':'Intercom OFF — click to start';c.videoReturn.hidden=!s?.returnCapability;c.videoReturn.disabled=unavailable||!s?.returnCapability;const assigned=!!(s?.returnEncoder||s?.returnSource);c.videoReturn.classList.toggle('on',assigned);c.videoReturn.setAttribute('aria-pressed',String(assigned));const state={'-1':'Error','0':'OFF','1':'ON','2':'Started','3':'Waiting'}[s?.returnStatus]||'Not reported';c.videoReturn.title='Video return'+(assigned?' assigned':'')+' · terminal '+state;}
function toggleIntercom(i){const s=nativeInput(i);if(!s||typeof s.intercom!=='boolean'){note('Intercom state has not been received from StreamHub.');return;}nativeAction({action:'intercom',input:i.id,enabled:!s.intercom},'IN:'+i.id);}
function openReturnPicker(i){const s=nativeInput(i);if(!i.connected||!s?.returnCapability){note('Video return unavailable on this terminal.');return;}if(returnDialog){returnDialog.d.close();returnDialog.d.remove();}const {d,list}=picker(`Input ${i.id} · Video return`);returnDialog={d,list};const choose=command=>{d.close();d.remove();returnDialog=null;nativeAction(command,'IN:'+i.id);};const off=button('Disconnect video return',()=>choose({action:'return',input:i.id,kind:'none'}));off.disabled=!s.returnEncoder&&!s.returnSource;list.append(off);let count=0;for(const e of nativeState.encoders)if(e.profile!=='-1'&&e.videoReturn&&(s.returnCapability&1)){const b=button(`Encoder ${e.id} · ${e.name}${e.enabled?' · ON':' · OFF'}`,()=>choose({action:'return',input:i.id,kind:'encoder',encoder:e.id}));b.classList.toggle('active',s.returnEncoder===e.id);list.append(b);count++;}for(const src of data.inputs){const ss=nativeInput(src);if(src.id!==i.id&&src.connected&&ss&&(s.returnCapability&ss.returnSourceProfile)){const b=button(`Input ${src.id} · ${src.name}`,()=>choose({action:'return',input:i.id,kind:'input',source:src.id}));b.classList.toggle('active',s.returnSource===src.id);list.append(b);count++;}}if(!count)list.append(el('p','No compatible video return source reported by StreamHub.'));}
