(()=>{
 const version='0.24.2',id='streamhub-virtual-panel-host',old=document.getElementById(id),origin=chrome.runtime.getURL('').slice(0,-1);
 if(old&&old.dataset.shVersion!==version){old.__shCleanup?.();old.remove();}
 if(old?.isConnected){old.hidden=!old.hidden;old.style.display=old.hidden?'none':'flex';old.shadowRoot.querySelector('iframe').contentWindow.postMessage({type:'sh-visible',visible:!old.hidden},origin);return;}
 const host=document.createElement('div');host.id=id;host.dataset.shVersion=version;host.style.cssText='all:initial;box-sizing:border-box;display:flex;position:fixed;left:24px;top:24px;width:1000px;height:740px;min-width:min(520px,calc(100vw - 16px));min-height:min(300px,calc(100vh - 16px));max-width:min(1000px,calc(100vw - 16px));max-height:calc(100vh - 16px);z-index:2147483647;background:#1e1f23;border:1px solid #454954;border-radius:8px;overflow:hidden;box-shadow:0 12px 40px #0008;';
 const shadow=host.attachShadow({mode:'open'}),style=document.createElement('style');style.textContent=':host{color-scheme:dark}*{box-sizing:border-box}section{display:flex;flex-direction:column;width:100%;height:100%;min-height:0}header{font:600 13px Arial;color:#e9eef4;background:#25272e;display:flex;align-items:center;gap:10px;padding:7px 10px;flex:none;cursor:move;touch-action:none;user-select:none}header span{flex:1}button{font:16px Arial;color:#e9eef4;background:#30333c;border:1px solid #454954;border-radius:3px;min-width:32px;height:28px;cursor:pointer}iframe{display:block;border:0;width:100%;flex:1;min-height:0;background:#1e1f23}.resize{position:absolute;bottom:0;right:0;width:30px;height:30px;z-index:2;cursor:nwse-resize;touch-action:none;background:linear-gradient(135deg,transparent 45%,#5e718888);border:0;border-radius:3px 0 0 0;padding:0}.resize:after{content:"";position:absolute;right:5px;bottom:5px;width:12px;height:12px;border-right:2px solid #d1dbe7;border-bottom:2px solid #d1dbe7}';
 const section=document.createElement('section'),head=document.createElement('header'),title=document.createElement('span');title.textContent='Haivision Streamhub Controller';const logo=document.createElement('img');logo.src=chrome.runtime.getURL('logo.png');logo.alt='';logo.style.cssText='width:24px;height:24px;object-fit:contain;flex:none';head.append(logo,title);
 const frame=document.createElement('iframe');frame.allow='clipboard-write';frame.src=chrome.runtime.getURL('app.html');frame.title='Haivision Streamhub Controller';const grip=document.createElement('button');grip.className='resize';grip.title='Resize panel';grip.setAttribute('aria-label','Resize panel');
 let drag=null,resizing=null,timer,autoHeight=true;const notify=()=>frame.contentWindow.postMessage({type:'sh-visible',visible:!host.hidden},origin);
 function clamp(){const r=host.getBoundingClientRect();host.style.left=Math.max(0,Math.min(r.left,innerWidth-r.width))+'px';host.style.top=Math.max(0,Math.min(r.top,innerHeight-r.height))+'px';}
 async function save(){if(!host.isConnected||host.hidden)return;const r=host.getBoundingClientRect();try{await chrome.storage.local.set({controllerGridPanelPositionV2:{left:r.left,top:r.top,width:r.width,height:r.height}});}catch(error){handleContextError(error);}}
 function handleContextError(error){if(/context invalidated/i.test(String(error?.message||error))){host.__shCleanup?.();host.remove();}else console.warn('RCP position could not be saved:',error?.message||error);}
 for(const [label,tip,fn] of [['↔','Fit panel',()=>{host.style.width=Math.min(1000,innerWidth-16)+'px';host.style.height=Math.min(740,innerHeight-16)+'px';clamp();save();}],['×','Hide',()=>{host.hidden=true;host.style.display='none';notify();}]]){const b=document.createElement('button');b.textContent=label;b.title=tip;b.onclick=fn;head.append(b);}
 head.onpointerdown=e=>{if(e.target.closest('button')||e.button!==0)return;const r=host.getBoundingClientRect();drag={x:e.clientX-r.left,y:e.clientY-r.top};head.setPointerCapture(e.pointerId);frame.style.pointerEvents='none';};head.onpointermove=e=>{if(!drag)return;host.style.left=e.clientX-drag.x+'px';host.style.top=e.clientY-drag.y+'px';clamp();};
 const stopDrag=()=>{drag=null;frame.style.pointerEvents='';save();};head.onpointerup=head.onpointercancel=head.onlostpointercapture=stopDrag;
 grip.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();const r=host.getBoundingClientRect();resizing={x:e.clientX,y:e.clientY,width:r.width,height:r.height};grip.setPointerCapture(e.pointerId);frame.style.pointerEvents='none';};grip.onpointermove=e=>{if(!resizing)return;host.style.width=Math.min(innerWidth-16,Math.max(520,Math.min(1000,resizing.width+e.clientX-resizing.x)))+'px';if(!autoHeight)host.style.height=Math.min(innerHeight-16,Math.max(300,resizing.height+e.clientY-resizing.y))+'px';clamp();};const stopResize=()=>{resizing=null;frame.style.pointerEvents='';save();};grip.onpointerup=grip.onpointercancel=grip.onlostpointercapture=stopResize;
 function layoutMessage(e){if(e.source!==frame.contentWindow||e.origin!==origin||e.data?.type!=='sh-panel-layout')return;autoHeight=e.data.devices===true;if(autoHeight&&Number.isFinite(e.data.height)){const height=Math.min(innerHeight-16,Math.max(300,e.data.height+head.getBoundingClientRect().height+2));if(Math.abs(host.getBoundingClientRect().height-height)>1)host.style.height=height+'px';clamp();}}
 window.addEventListener('message',layoutMessage);
 section.append(head,frame,grip);shadow.append(style,section);document.documentElement.append(host);const observer=new ResizeObserver(()=>{if(!host.isConnected){observer.disconnect();return;}clamp();clearTimeout(timer);timer=setTimeout(save,250);});observer.observe(host);window.addEventListener('resize',clamp);const stopNativePreview=installTabBridge(host,frame,origin);host.__shCleanup=()=>{window.removeEventListener('message',layoutMessage);stopNativePreview();observer.disconnect();clearTimeout(timer);window.removeEventListener('resize',clamp);};try{chrome.storage.local.get('controllerGridPanelPositionV2').then(({controllerGridPanelPositionV2:p})=>{if(p){host.style.left=p.left+'px';host.style.top=p.top+'px';}clamp();}).catch(handleContextError);}catch(error){handleContextError(error);}
})();
