const previewCache=new Map();let previewsLoading=false,mojoPreview=null,lastPreviewRequest=0,previewImmediate=false;
function makePreview(parent,before){const c={preview:el('div',undefined,'input-preview'),image:el('img'),previewLabel:el('span','No connected device','preview-label'),meters:el('div',undefined,'audio-meters'),format:el('p',undefined,'signal-format')};c.image.alt='MoJo device preview';c.image.hidden=true;c.preview.append(c.image,c.previewLabel,c.meters,c.format);parent.insertBefore(c.preview,before||null);return c;}
function canPreviewInput(i){return !!i&&i.connected;}
function paintPreview(c,i){const frame=i?previewCache.get(i.id):null,valid=canPreviewInput(i)&&online&&frame?.uid===i.uid&&!frame.error&&frame.thumbnail&&Date.now()-frame.time<7000;if(!canPreviewInput(i)&&i)previewCache.delete(i.id);if(valid){if(c.image.getAttribute('src')!==frame.thumbnail)c.image.src=frame.thumbnail;c.image.hidden=false;}else{c.image.hidden=true;c.image.removeAttribute('src');}c.previewLabel.hidden=!!valid;text(c.previewLabel,!canPreviewInput(i)?'No connected device':frame?.error?'Preview unavailable':'Waiting for device preview…');text(c.format,valid?i.inputInfo:'');c.meters.replaceChildren();if(valid)for(const [n,level]of(frame.audioLevels||[]).entries()){const meter=el('span',undefined,'audio-meter'),fill=el('i');fill.style.height=level.peak===null?'0%':`${(level.peak+50)*2}%`;meter.title=`Audio ${n+1}`;meter.append(fill);c.meters.append(meter);}}
function syncPreviewCard(c,i){if(!c.preview)Object.assign(c,makePreview(c.main,c.name));c.card.classList.add('preview-tile');c.name.hidden=false;paintPreview(c,i);}
function attachMojoPreview(parent){const wrap=el('div',undefined,'mojo-monitor');mojoPreview=makePreview(wrap);parent.append(wrap);syncMojoPreview();}
function syncMojoPreview(){if(mojoPreview&&mojo)paintPreview(mojoPreview,data.inputs.find(i=>i.id===mojo.input));}
function requestPreviewNow(){previewImmediate=true;pollPreviews();}
async function pollPreviews(){if(previewsLoading||!pollingAllowed()||!visible||!online||busy)return;if(!previewImmediate&&Date.now()-lastPreviewRequest<(mojo?400:2000))return;previewImmediate=false;lastPreviewRequest=Date.now();const rows=(mojo?data.inputs.filter(i=>i.id===mojo.input):tab==='inputs'?data.inputs:tab==='outputs'?data.inputs.filter(i=>data.outputs.some(o=>o.enabled&&o.source===i.id)):mojoInputs).filter(i=>canPreviewInput(i)&&!(previewCache.get(i.id)?.source==='socket'&&previewCache.get(i.id)?.uid===i.uid&&Date.now()-previewCache.get(i.id).time<3000)),ids=rows.map(i=>i.id).slice(0,16);if(!ids.length){for(const c of cards.values())if(c.item&&tab!=='encoders'){if(c.isInput)paintPreview(c,c.item);else syncOutputPreview(c,c.item);};syncMojoPreview();return;}const e=epoch,identities=new Map(rows.map(i=>[i.id,i.uid]));previewsLoading=true;try{const d=await call({type:'previews',inputs:ids});if(e!==epoch)return;for(const p of d.previews){if(data.inputs.find(i=>i.id===p.id)?.uid===identities.get(p.id))previewCache.get(p.id)?.source==='socket'&&Date.now()-previewCache.get(p.id).time<3000?null:previewCache.set(p.id,{...p,uid:identities.get(p.id)});}}catch{for(const id of ids)previewCache.delete(id);}finally{previewsLoading=false;for(const c of cards.values())if(c.item&&tab!=='encoders'){if(c.isInput)paintPreview(c,c.item);else syncOutputPreview(c,c.item);};syncMojoPreview();if(previewImmediate&&pollingAllowed())pollPreviews();}}
function sizeChannelGrid(){}
registerPoll(pollPreviews,400);

window.addEventListener('message',e=>{if(e.source!==parent||e.data?.type!=='sh-native-preview'||e.data.base!==base||!pollingAllowed()||!online)return;const p=e.data,i=data.inputs.find(i=>i.id===p.id&&i.connected);if(!i||typeof p.thumbnail!=='string'||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=\r\n]+$/.test(p.thumbnail)||p.thumbnail.length>1500030)return;previewCache.set(i.id,{id:i.id,uid:i.uid,thumbnail:p.thumbnail,source:'socket',time:Date.now(),audioLevels:(p.audioLevels||[]).map(a=>({peak:Number.isFinite(a.peak)?Math.max(-50,Math.min(0,a.peak)):null}))});for(const c of cards.values())if(tab!=='encoders'&&c.isInput&&c.item?.id===i.id)paintPreview(c,c.item);else if(tab!=='encoders'&&!c.isInput&&c.item?.source===i.id)syncOutputPreview(c,c.item);syncMojoPreview();});
const outputPreviewCache=new Map();
function syncOutputPreview(c,o){if(!c.preview)Object.assign(c,makePreview(c.main,c.name));const native=outputPreviewCache.get(o.type+':'+o.id),input=o.source?data.inputs.find(i=>i.id===o.source):null,sourceFrame=input?previewCache.get(input.id):null;const nativeValid=native&&native.base===base&&Date.now()-native.time<7000;const frame=nativeValid?native:sourceFrame,valid=online&&o.enabled&&frame?.thumbnail&&!frame.error&&Date.now()-frame.time<7000&&(nativeValid||sourceFrame?.uid===input?.uid);if(valid){if(c.image.getAttribute('src')!==frame.thumbnail)c.image.src=frame.thumbnail;c.image.hidden=false;}else{c.image.hidden=true;c.image.removeAttribute('src');}c.previewLabel.hidden=!!valid;text(c.previewLabel,!o.enabled?'Output OFF':!o.source?'Unassigned output':'Waiting for preview…');text(c.format,valid?(nativeValid?'Output preview':'Source preview'):'');c.meters.replaceChildren();}
window.addEventListener('message',e=>{if(e.source!==parent||e.data?.type!=='sh-native-output-preview'||e.data.base!==base||!pollingAllowed()||!online)return;const p=e.data;if(!['SDI','NDI'].includes(p.kind)||!Number.isInteger(p.id)||typeof p.thumbnail!=='string'||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=\r\n]+$/.test(p.thumbnail)||p.thumbnail.length>1500030)return;outputPreviewCache.set(p.kind+':'+p.id,{...p,time:Date.now()});for(const c of cards.values())if(tab!=='encoders'&&!c.isInput&&c.item)syncOutputPreview(c,c.item);});

window.addEventListener('message',e=>{if(e.source!==parent||e.data?.type!=='sh-native-network'||e.data.base!==base||!pollingAllowed()||!connected)return;call({type:'nativeNetwork',base,network:e.data.network}).catch(()=>{});});

window.addEventListener('message',e=>{if(e.source===parent&&e.data?.type==='sh-preview-status'&&e.data.base===base&&pollingAllowed()&&typeof e.data.message==='string'&&e.data.message.length<=256)note(e.data.message);});

window.addEventListener('message',e=>{if(e.source!==parent||e.data?.type!=='sh-native-device-recording'||e.data.base!==base||!pollingAllowed()||!connected||!Array.isArray(e.data.devices))return;for(const d of e.data.devices){if(!Number.isInteger(d.id)||typeof d.recording!=='boolean')continue;const i=data.inputs.find(i=>i.id===d.id&&i.connected);if(!i)continue;terminalRecordingStates.set(base+':'+i.id,{uid:i.uid,recording:d.recording});i.deviceRecording=d.recording;}render();});
