/* Native values remain native. Shutter conversion requires an explicit device profile. */
window.RCP={
 shutterSteps(s,profile={}){const bounds=this.bounds('ShutterSpeed',s,profile);return bounds?[25,30,40,50,60,80,100,120,125,160,200,250,320,400,500,640,800,1000,1250,1600,2000,2500,3200,4000,5000,6400,8000,10000,12800,16000,20000,25600].filter(v=>v>=bounds[0]&&v<=bounds[1]):[];},
 shutterIndex(value,s,profile={}){const steps=this.shutterSteps(s,profile);return steps.reduce((best,v,n)=>Math.abs(Math.log(v/value))<Math.abs(Math.log(steps[best]/value))?n:best,0);},

 bounds(group,s,profile={}){let limit=group==='WB'?[1500,10000]:group==='ISO'?[100,6400]:group==='ShutterSpeed'?[25,25600]:group==='Zoom'?[1,Infinity]:group==='AudioGain'?[-60,12]:[0,Infinity];if(!s||!Object.keys(s).length)return null;const r=s[group+'Range'];if(r!==undefined&&(!Array.isArray(r)||r.length!==2||!r.every(Number.isFinite)||r[1]<=r[0]))return null;if(Array.isArray(r)&&r.length===2&&r.every(Number.isFinite)&&r[1]>r[0]){let range=r;if(group==='ShutterSpeed'){if(!profile.shutterUnit||r[0]<=0)return null;range=profile.shutterUnit==='seconds'?[1/r[1],1/r[0]]:profile.shutterUnit==='microseconds'?[1000000/r[1],1000000/r[0]]:r;}if(group==='WB'&&range[1]<1000)return null;limit=[Math.max(limit[0],range[0]),Math.min(limit[1],range[1])];}if(group==='ShutterSpeed'&&!profile.shutterUnit)return null;return limit[0]<=limit[1]?limit:null;},
 fromApi(group,value,profile={}){if(!Number.isFinite(value)||group==='WB'&&value<1000)return null;if(group==='ShutterSpeed'){if(!profile.shutterUnit||value<=0)return null;return profile.shutterUnit==='seconds'?1/value:profile.shutterUnit==='microseconds'?1000000/value:value;}return value;},
 toApi(group,value,profile={}){if(group==='ShutterSpeed'){if(!profile.shutterUnit)throw Error('Choose shutter API units in Device settings first.');return profile.shutterUnit==='seconds'?1/value:Math.round(profile.shutterUnit==='microseconds'?1000000/value:value);}return ['WB','ISO'].includes(group)?Math.round(value):value;},
 parse(group,text){const t=String(text).trim().replace(/\s*(K|x|dB)$/i,'');return Number(group==='ShutterSpeed'?t.replace(/^1\s*\/\s*/,''):t);},
 format(group,value){if(value===null||!Number.isFinite(value))return '—';if(group==='ShutterSpeed')return '1/'+Math.round(value);if(group==='WB'||group==='ISO')return String(Math.round(value));return group==='Zoom'?value.toFixed(2):group==='AudioGain'?value.toFixed(1):value.toFixed(3);}
};
