const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');const source=fs.readFileSync(path.resolve(__dirname,'../extension/app.js'),'utf8');
const functions=source.slice(source.indexOf('function confirmAssignment()'),source.indexOf('function picker('));
function fixture({start=false,enabled=false,failed=false,replaced=false}={}){const writes=[],notes=[],row={id:1,uid:'phone',name:'Phone',canPower:true,enabled},dialog={classList:{add(){}},closed:false,removed:false,close(){this.closed=true},remove(){this.removed=true}},list={classList:{add(){}},children:[],append(...items){this.children.push(...items)}};
 const c={source:row,data:{inputs:[row]},selected:new Set(['IP:1','NDI:1']),busy:false,online:true,epoch:1,locks:new Set(),note:n=>notes.push(n),render(){},switchTab(){},picker:()=>({d:dialog,list}),el:(tag,text)=>({tag,text}),button:(label,onclick)=>({label,onclick}),runAction:async fn=>fn(),update:s=>{c.data=s},write:async m=>{writes.push(m);if(m.type==='route')return {results:[{ok:true,message:'OK'},{ok:!failed,message:failed?'Failed':'OK'}],snapshot:{inputs:[{...row,uid:replaced?'replacement':'phone'}]}};return {snapshot:{inputs:[{...row,enabled:true,status:2}]}}}};vm.createContext(c);vm.runInContext(functions,c);return {c,writes,notes,dialog,list};}
(async()=>{
 for(const start of [false,true]){const f=fixture();f.c.confirmAssignment();assert.equal(f.writes.length,0,'opening dialog cannot mutate server');assert(f.list.children.some(b=>b.label==='Only assign'));const choice=f.list.children.find(b=>b.label===(start?'LIVE':'Only assign'));choice.onclick();await new Promise(r=>setImmediate(r));assert.equal(f.writes[0].type,'route');assert.equal(f.writes.length,start?2:1);if(start){assert.equal(f.writes[1].type,'inputPower');assert.equal(f.writes[1].action,'enable');assert.equal(f.writes[1].expectedUID,'phone');}assert(f.dialog.closed&&f.dialog.removed);}
 for(const flags of [{failed:true},{enabled:true},{replaced:true}]){const f=fixture(flags);await f.c.outputAction('route',undefined,['IP:1','NDI:1'],{id:1,uid:'phone',start:true});assert.equal(f.writes.length,1,'no start after failed route, already ON or replacement');}
 const f=fixture();f.c.confirmAssignment();f.c.source={id:1,uid:'replacement'};f.list.children.find(b=>b.label==='LIVE').onclick();assert.equal(f.writes.length,0,'changed dialog source must not route');
 console.log('PASS ASSIGN choice: no writes before choice, route-only, route then ON, no duplicate start, partial-failure and source-identity guards. Simulated API.');
})().catch(e=>{console.error(e);process.exit(1)});
